/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as DevmodeRouteImport } from "./routes/devmode"
import { Route as IndexRouteImport } from "./routes/index"

const DevmodeRoute = DevmodeRouteImport.update({
  id: "/devmode",
  path: "/devmode",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/devmode": typeof DevmodeRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/devmode": typeof DevmodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/devmode": typeof DevmodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/devmode"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/devmode"
  id: "__root__" | "/" | "/devmode"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevmodeRoute: typeof DevmodeRoute
}

declare module "@tanstack/solid-router" {
  interface FileRoutesByPath {
    "/devmode": {
      id: "/devmode"
      path: "/devmode"
      fullPath: "/devmode"
      preLoaderRoute: typeof DevmodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevmodeRoute: DevmodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
